"""Parser tests for the complete stock-page QuoteBundle (Card 0.1-G).

RED-first: every test below fails until ``finvizp._parsers.quote`` exists.
Fixtures are minimal scrubbed structures generated by ``_build.py``; no live
HTML, scripts, ads, or tracking.
"""

from __future__ import annotations

import datetime as dt
from pathlib import Path

import pyarrow as pa
import pytest

from finvizp import arrow as fa
from finvizp import schemas
from finvizp._parsers import quote as quote_parser
from finvizp.errors import FetchWarning, FinvizParseError
from finvizp.models import QuoteBundle

# Builder-level dataset field helper used by schema-shape assertions.
dataset_field_names = fa.dataset_field_names

FIXTURES = Path(__file__).parent / "fixtures" / "quote"
FETCHED_AT = dt.datetime(2026, 8, 28, 14, 30, tzinfo=dt.UTC)
RESPONSE_DATE = dt.date(2026, 8, 28)


def _page(name: str = "stock-current.html") -> str:
    return (FIXTURES / name).read_text("utf-8")


def _parse(name: str = "stock-current.html", **kwargs: object) -> QuoteBundle:
    kwargs.setdefault("fetched_at", FETCHED_AT)
    kwargs.setdefault("response_date", RESPONSE_DATE)
    return quote_parser.parse_quote_page(_page(name), **kwargs)  # type: ignore[arg-type]


def _parse_html(html: str, **kwargs: object) -> QuoteBundle:
    kwargs.setdefault("fetched_at", FETCHED_AT)
    kwargs.setdefault("response_date", RESPONSE_DATE)
    return quote_parser.parse_quote_page(html, **kwargs)  # type: ignore[arg-type]


def _rows(table: pa.Table | None) -> list[dict[str, object]]:
    assert table is not None
    return table.to_pylist()


# --- snapshot: all six regions merged, no first-table truncation ------------


def test_all_six_snapshot_regions_discovered_and_merged() -> None:
    bundle = _parse()
    assert bundle.snapshot is not None
    assert bundle.snapshot.num_rows == 1
    names = bundle.snapshot.schema.names
    assert names == list(dataset_field_names("quote_snapshot"))
    # One field from each of the six physical tables must survive the merge
    # (first-table truncation would lose the later groups).
    row = _rows(bundle.snapshot)[0]
    assert row["market_cap"] == 3.10e12
    assert row["pe_ratio"] == 32.10
    assert row["eps_ttm"] == 8.20
    assert row["ex_dividend_date"] == dt.date(2026, 8, 10)
    assert row["earnings_date"] == "Jul 30 AMC"
    assert row["sma20_percent"] == pytest.approx(0.024)
    assert row["float_shares"] == 15.0e9
    assert row["beta"] == 1.24
    assert row["volume"] == 52_400_000
    assert row["employees"] == 166000
    assert row["ipo_date"] == dt.date(1980, 12, 12)


def test_snapshot_raw_and_status_companions() -> None:
    row = _rows(_parse().snapshot)[0]
    assert row["market_cap_raw"] == "3.10T"
    assert row["price_raw"] == "315.46"
    assert row["change_percent_raw"] == "0.28%"
    assert row["earnings_date"] == "Jul 30 AMC"
    assert row["price"] == 315.46


def test_reordered_fixture_produces_equivalent_records() -> None:
    current = _parse("stock-current.html")
    reordered = _parse("stock-reordered.html")
    assert current.snapshot is not None and reordered.snapshot is not None
    # Deterministic registry order: identical schemas and rows.
    assert reordered.snapshot.equals(current.snapshot)

    # Physically permuting tables and swapping row pairs within one table
    # must preserve every per-table label->value grouping, wherever it sits.
    def pair_groups(bundle: QuoteBundle) -> list[list[tuple[str, str]]]:
        assert bundle.snapshot_tables is not None
        return sorted(
            sorted(
                zip(
                    t.column("label").to_pylist(),
                    t.column("value").to_pylist(),
                    strict=True,
                )
            )
            for t in bundle.snapshot_tables.values()
        )

    assert pair_groups(reordered) == pair_groups(current)


def test_reordered_labels_and_values_stay_paired() -> None:
    row = _rows(_parse("stock-reordered.html").snapshot)[0]
    assert row["price"] == 315.46
    assert row["market_cap"] == 3.10e12
    assert row["eps_ttm"] == 8.20


def test_snapshot_per_table_projection() -> None:
    bundle = _parse()
    tables = bundle.snapshot_tables
    assert len(tables) == 6
    labels = {frozenset(t.column("label").to_pylist()) for t in tables.values()}
    # Each physical table is preserved with its own labels.
    assert any("Market Cap" in s for s in labels)
    assert any("Volume" in s for s in labels)


def test_fixture_represents_all_sixteen_page_tables() -> None:
    # The verified stock page carries sixteen tables; the minimal structural
    # fixture must represent all of them (six snapshot + ten auxiliary).
    assert _page().count("<table") == 16


def test_snapshot_projection_excludes_auxiliary_tables() -> None:
    # Auxiliary page furniture must not leak into the snapshot projections:
    # still exactly the six snapshot regions, labels untouched.
    labels = [
        label
        for table in _parse().snapshot_tables.values()
        for label in table.column("label").to_pylist()
    ]
    assert len(labels) == 19
    assert "Insider Trading" not in labels and "Date" not in labels


def test_exactly_six_snapshot_regions_required() -> None:
    # The verified page carries six snapshot-table2 regions; removing one is
    # required-structure drift and must raise, not silently parse as COMPLETE.
    html = _page().replace("snapshot-table2", "gone-table", 1)
    with pytest.raises(FinvizParseError):
        _parse_html(html)


def test_malformed_snapshot_pair_structure_raises() -> None:
    # An odd cell count inside a snapshot region is malformed label/value
    # pair structure: fail typed instead of pairing across the boundary.
    html = _page().replace(
        '<div class="snapshot-td-label">Beta</div></td>',
        '<div class="snapshot-td-label">Beta</div></td>'
        '<td class="snapshot-td2"><div class="snapshot-td-content">orphan</div></td>',
        1,
    )
    with pytest.raises(FinvizParseError):
        _parse_html(html)


# --- header: identity and classification ------------------------------------


def test_header_identity_fields() -> None:
    row = _rows(_parse().snapshot)[0]
    assert row["symbol"] == "AAPL"
    assert row["company"] == "Sample Technologies Inc"
    assert row["sector"] == "Technology"
    assert row["industry"] == "Hardware"
    assert row["country"] == "USA"
    assert row["exchange"] == "NASDAQ"


# --- description ------------------------------------------------------------


def test_description_relation() -> None:
    table = _parse().description
    rows = _rows(table)
    assert table is not None and table.num_rows == 1
    assert rows[0]["description"].startswith("Sample Technologies, Inc. engages")


# --- ratings ----------------------------------------------------------------


def test_ratings_relation() -> None:
    table = _parse().ratings
    assert table is not None and table.num_rows == 3
    rows = _rows(table)
    first = rows[0]
    assert first["symbol"] == "AAPL"
    assert first["status"] == "Upgrade"
    assert first["analyst"] == "Redburn"
    # Registry keeps the rating change as its text display (no numeric scale).
    assert first["rating"] == "Neutral → Buy"
    assert first["price_target"] == 230.0
    # Temporal: Aug-17-26 is a complete date display -> exact midnight Eastern.
    assert first["published_at"] == dt.datetime(2026, 8, 17, 4, 0, tzinfo=dt.UTC)
    # The raw companion is the parser's builder-facing display.
    assert first["published_at_raw"] == "2026-08-17 00:00"
    assert first["published_at_status"] == "exact"


def test_ratings_rows_preserve_order() -> None:
    rows = _rows(_parse().ratings)
    assert [r["analyst"] for r in rows] == ["Redburn", "Jefferies", "DZ Bank"]


# --- news -------------------------------------------------------------------


def test_news_relation_with_temporal_anchoring() -> None:
    table = _parse().news
    assert table is not None and table.num_rows == 4
    rows = _rows(table)
    assert rows[0]["title"] == "First headline"
    assert rows[0]["url"] == "https://example.com/a"
    assert rows[0]["publisher"] == "Example News"
    # "Today 05:25AM" anchors to the response date in US Eastern; the raw
    # companion is the parser's builder-facing display ("Today" stripped).
    assert rows[0]["published_at"] == dt.datetime(2026, 8, 28, 9, 25, tzinfo=dt.UTC)
    assert rows[0]["published_at_raw"] == "05:25"
    assert rows[0]["published_at_status"] == "anchored"
    # Time-only display also anchors.
    assert rows[1]["published_at"] == dt.datetime(2026, 8, 28, 13, 0, tzinfo=dt.UTC)
    assert rows[1]["published_at_status"] == "anchored"
    # "Yesterday 11:30PM" resolves to the exact prior-day Eastern instant.
    assert rows[3]["published_at"] == dt.datetime(2026, 8, 28, 3, 30, tzinfo=dt.UTC)
    assert rows[3]["published_at_raw"] == "2026-08-27 23:30"
    assert rows[3]["published_at_status"] == "exact"


def test_news_publisher_parentheses_stripped() -> None:
    rows = _rows(_parse().news)
    assert rows[0]["publisher"] == "Example News"


# --- insider ----------------------------------------------------------------


def test_insider_relation() -> None:
    table = _parse().insider
    assert table is not None and table.num_rows == 2
    rows = _rows(table)
    sale = rows[0]
    assert sale["owner"] == "Doe Jane"
    assert sale["relationship"] == "Director"
    assert sale["transaction_date"] == dt.date(2026, 8, 25)
    assert sale["transaction_type"] == "Sale"
    assert sale["cost"] == 310.95
    assert sale["shares"] == 1439.0
    assert sale["value"] == 447457.0
    assert sale["shares_total"] == 37229.0
    assert sale["sec_form_url"] == "http://www.sec.gov/Archives/edgar/data/1/form4.xml"


def test_insider_header_driven_column_order() -> None:
    # The reordered fixture physically permutes insider header columns (with
    # their cells); the parser must map by header text, not position.
    rows = _rows(_parse("stock-reordered.html").insider)
    assert rows[0]["cost"] == 310.95
    assert rows[0]["owner"] == "Doe Jane"
    assert rows[0]["transaction_date"] == dt.date(2026, 8, 25)
    assert rows[1]["transaction_type"] == "Buy"


# --- peers and ETF holders ---------------------------------------------------


def test_peers_relation() -> None:
    table = _parse().peers
    assert table is not None and table.num_rows == 2
    rows = _rows(table)
    assert rows[0]["peer"] == "MSFT"
    assert rows[0]["rank"] == 1
    assert rows[0]["market_cap"] == 3.73913e12
    assert rows[0]["market_cap_raw"] == "3739.13B"
    assert rows[1]["peer"] == "GOOG"
    assert rows[1]["rank"] == 2


def test_etf_holders_relation() -> None:
    table = _parse().etf_holders
    assert table is not None and table.num_rows == 2
    rows = _rows(table)
    assert rows[0]["etf"] == "VTI"
    assert rows[0]["rank"] == 1
    # AUM values are not weights; weight stays null and raw lands in extra.
    assert rows[0]["weight_percent"] is None
    assert rows[1]["etf"] == "QQQ"


# --- signals and links --------------------------------------------------------


def test_signals_relation() -> None:
    table = _parse().signals
    assert table is not None and table.num_rows == 3
    rows = _rows(table)
    assert rows[0]["signal"] == "Top Gainers"
    assert rows[0]["url"].endswith("s=ta_topgainers")
    assert rows[2]["signal"] == "Major News"


# --- artifacts ---------------------------------------------------------------


def test_chart_artifact_descriptors() -> None:
    bundle = _parse()
    kinds = {a.kind for a in bundle.artifacts}
    assert kinds == {"chart"}
    daily = [a for a in bundle.artifacts if a.timeframe == "d"]
    weekly = [a for a in bundle.artifacts if a.timeframe == "w"]
    assert len(daily) == 1 and len(weekly) == 1
    assert daily[0].source_url.endswith("chart.ashx?t=AAPL&p=d&tkr117=y")
    assert daily[0].media_type == "image/png"
    assert daily[0].symbol == "AAPL"
    assert daily[0].fetched_at == FETCHED_AT


def test_artifact_immutability() -> None:
    artifact = _parse().artifacts[0]
    with pytest.raises(AttributeError):
        artifact.kind = "nope"  # type: ignore[misc]


# --- structural fingerprint ---------------------------------------------------


def test_structural_fingerprint_stable_and_input_sensitive() -> None:
    bundle = _parse()
    assert isinstance(bundle.fingerprint, str)
    assert len(bundle.fingerprint) == 64
    assert bundle.fingerprint == _parse().fingerprint
    assert bundle.fingerprint != _parse("stock-reordered.html").fingerprint


# --- required/optional region drift -------------------------------------------


def test_missing_snapshot_is_required_parse_error() -> None:
    html = _page().replace("snapshot-table2", "gone-table")
    with pytest.raises(FinvizParseError):
        quote_parser.parse_quote_page(html, fetched_at=FETCHED_AT, response_date=RESPONSE_DATE)


def test_missing_optional_region_warns_not_raises() -> None:
    html = _page().replace("js-table-ratings", "gone-ratings")
    warnings: list[FetchWarning] = []
    bundle = quote_parser.parse_quote_page(
        html,
        fetched_at=FETCHED_AT,
        response_date=RESPONSE_DATE,
        on_warning=warnings.append,
    )
    assert bundle.ratings is None
    assert any(w.code == "missing_region" for w in warnings)
    # Partial status: some relations present, one missing.
    assert bundle.status.name == "PARTIAL"


def test_strict_schema_promotes_missing_optional_region() -> None:
    html = _page().replace("js-table-ratings", "gone-ratings")
    with pytest.raises(FinvizParseError):
        quote_parser.parse_quote_page(
            html,
            fetched_at=FETCHED_AT,
            response_date=RESPONSE_DATE,
            strict_schema=True,
        )


def test_complete_page_is_complete_status() -> None:
    assert _parse().status.name == "COMPLETE"


def test_complete_page_has_no_conversion_warnings_and_strict_passes() -> None:
    # The verified fixture is standard content, not drift: a structurally
    # complete page must parse warning-free (no conversion_failed) and pass
    # strict_schema.
    warnings: list[FetchWarning] = []
    _parse(on_warning=warnings.append)
    assert not [w for w in warnings if w.code == "conversion_failed"]
    strict = _parse(strict_schema=True)
    assert strict.status.name == "COMPLETE"


# --- additive snapshot labels -> extra_fields + warning ------------------------


def test_additive_snapshot_label_flows_to_extra_fields() -> None:
    # Insert one unmapped label into an existing pair; it must reach
    # extra_fields verbatim with an unknown_field warning, not disappear.
    html = _page().replace(
        '<div class="snapshot-td-label">Beta</div></td>'
        '<td class="snapshot-td2"><div class="snapshot-td-content">1.24</div></td>',
        '<div class="snapshot-td-label">Beta</div></td>'
        '<td class="snapshot-td2"><div class="snapshot-td-content">1.24</div></td>'
        '<td class="snapshot-td2"><div class="snapshot-td-label">Brand New Ratio</div>'
        '</td><td class="snapshot-td2"><div class="snapshot-td-content">3.50</div></td>',
        1,
    )
    warnings: list[FetchWarning] = []
    bundle = quote_parser.parse_quote_page(
        html, fetched_at=FETCHED_AT, response_date=RESPONSE_DATE, on_warning=warnings.append
    )
    row = _rows(bundle.snapshot)[0]
    assert row["extra_fields"] == [("Brand New Ratio", "3.50")]
    assert any(w.code == "unknown_field" for w in warnings)


def test_unmapped_label_is_not_silent() -> None:
    # Every provider label the parser knows about must land in a registry field;
    # an unmapped one must warn. The full fixture is fully mapped.
    warnings: list[FetchWarning] = []
    _parse(on_warning=warnings.append)
    assert not [w for w in warnings if w.code == "unknown_field"]


# --- empty relations and empty schemas ----------------------------------------


def test_missing_optional_regions_yield_none_and_empty_schema_helpers() -> None:
    html = "<html><body><h1>nothing here</h1></body></html>"
    with pytest.raises(FinvizParseError):
        quote_parser.parse_quote_page(html, fetched_at=FETCHED_AT, response_date=RESPONSE_DATE)


def test_all_news_rows_removed_keeps_empty_registered_table() -> None:
    # Present structure with zero rows: the no-results state is positively
    # recognized, so the relation keeps its registered empty Arrow table and
    # the bundle stays COMPLETE (structure presence, not row count, decides).
    html = _page()
    start = html.index('<table width="100%" cellpadding="1"')
    end = html.index("</table>", start) + len("</table>")
    html = (
        html[:start]
        + (
            '<table width="100%" cellpadding="1" cellspacing="0" border="0" '
            'id="news-table" class="fullview-news-outer news-table" data-ticker="AAPL"></table>'
        )
        + html[end:]
    )
    bundle = _parse_html(html)
    assert bundle.news is not None
    assert bundle.news.num_rows == 0
    assert bundle.news.schema.names == list(dataset_field_names("quote_news"))
    assert bundle.status.name == "COMPLETE"


def test_each_tabular_relation_present_but_empty_keeps_registered_schema() -> None:
    # Every tabular relation: structure present, all rows removed -> empty
    # registered table, never None.
    def stripped(marker: str, replacement: str) -> str:
        html = _page()
        start = html.index(marker)
        end = html.index("</table>", start) + len("</table>")
        return html[:start] + replacement + html[end:]

    empty_news = (
        '<table width="100%" cellpadding="1" cellspacing="0" border="0" '
        'id="news-table" class="fullview-news-outer news-table" data-ticker="AAPL"></table>'
    )
    empty_ratings = (
        '<table width="100%" class="js-table-ratings styled-table-new" '
        'cellpadding="0" cellspacing="0" border="0"><thead><tr>'
        "<th>Date</th><th>Action</th><th>Analyst</th><th>Rating Change</th>"
        "<th>Price Target Change</th></tr></thead></table>"
    )
    empty_insider = (
        '<table cellpadding="0" cellspacing="0" width="100%" '
        'class="body-table styled-table-new"><thead><tr><th>Insider Trading</th>'
        "<th>Relationship</th><th>Date</th><th>Transaction</th><th>Cost</th>"
        "<th>#Shares</th><th>Value ($)</th><th>#Shares Total</th>"
        "<th>SEC Form 4</th></tr></thead></table>"
    )
    empty_signals = (
        '<table width="100%" cellpadding="0" cellspacing="0" border="0" '
        'class="fullview-links table-fixed"><tbody><tr>'
        '<td class="js-quote-correlation-links-container">'
        '<div class="flex"><div class="flex-1"></div></div></td></tr></tbody></table>'
    )
    cases = [
        ('<table width="100%" class="js-table-ratings', empty_ratings),
        ('<table width="100%" cellpadding="1"', empty_news),
        ('<table cellpadding="0" cellspacing="0" width="100%"', empty_insider),
        ('<table width="100%" cellpadding="0"', empty_signals),
    ]
    for marker, replacement in cases:
        bundle = _parse_html(stripped(marker, replacement))
        name = {
            empty_ratings: "ratings",
            empty_news: "news",
            empty_insider: "insider",
            empty_signals: "signals",
        }[replacement]
        table = getattr(bundle, name)
        assert table is not None, name
        assert table.num_rows == 0, name
        assert table.schema.names == list(dataset_field_names(f"quote_{name}")), name


def test_peers_and_etf_holders_present_but_empty_keep_registered_schema() -> None:
    # Removing the ticker spans (but not the introducing Peers / Held by
    # links) is a present-but-empty structure, not a missing region.
    html = _page().replace(" data-boxover-ticker=", " data-gone-ticker=")
    bundle = _parse_html(html)
    for name in ("peers", "etf_holders"):
        table = getattr(bundle, name)
        assert table is not None, name
        assert table.num_rows == 0, name
        assert table.schema.names == list(dataset_field_names(f"quote_{name}")), name


def test_absent_structure_still_means_missing_region() -> None:
    # Contrast case: removing the structure itself (not its rows) is a
    # missing optional region -> warning + None + PARTIAL.
    html = _page().replace("js-table-ratings", "gone-ratings")
    warnings: list[FetchWarning] = []
    bundle = _parse_html(html, on_warning=warnings.append)
    assert bundle.ratings is None
    assert any(w.code == "missing_region" for w in warnings)
    assert bundle.status.name == "PARTIAL"


def test_empty_schema_shapes_for_every_relation() -> None:
    for name in (
        "quote_snapshot",
        "quote_description",
        "quote_ratings",
        "quote_news",
        "quote_insider",
        "quote_peers",
        "quote_etf_holders",
        "quote_signals",
    ):
        table = schemas.arrow_schema(name)
        assert isinstance(table, pa.Schema), name


# --- bundle immutability -------------------------------------------------------


def test_bundle_is_frozen() -> None:
    bundle = _parse()
    with pytest.raises(AttributeError):
        bundle.symbol = "MSFT"  # type: ignore[misc]
    with pytest.raises(AttributeError):
        bundle.snapshot = None  # type: ignore[misc]


def test_bundle_containers_are_immutable() -> None:
    bundle = _parse()
    with pytest.raises(TypeError):
        bundle.snapshot_tables["x"] = None  # type: ignore[index]
    with pytest.raises(AttributeError):
        bundle.artifacts[0].kind = "x"  # type: ignore[misc]


def test_bundle_defaults_and_relations() -> None:
    bundle = QuoteBundle(symbol="AAPL", fetched_at=FETCHED_AT)
    assert bundle.snapshot is None
    assert bundle.status.name == "EMPTY"
    assert bundle.snapshot_tables == {}
    assert bundle.artifacts == ()


# --- fingerprint dataset coverage ---------------------------------------------


def test_registry_has_all_bundle_datasets() -> None:
    names = set(schemas.dataset_names())
    for required in (
        "quote_snapshot",
        "quote_description",
        "quote_ratings",
        "quote_news",
        "quote_insider",
        "quote_peers",
        "quote_etf_holders",
        "quote_signals",
    ):
        assert required in names
